#!/bin/bash -e

# This script deletes a zone from the nameserver.

# Copyright 2016, Markus Gutschke

export LC_ALL=C
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Use lxc, if necessary
LXC=
if lxc info pdns >&/dev/null; then
  LXC="lxc exec pdns --"
fi

db="/var/lib/powerdns/pdns.sqlite3"
SQL_Escape() { printf '%s' "'${*//\'/\'\'}'"; }

usage() {
  echo "${0##*/} { zone }" >&2
  exit 1
}

# Basic sanity checking.
[ $# -eq 1 ] || usage
$LXC pdnsutil list-zone "${1}" >&/dev/null || {
  echo "Zone \"$1\" does not exist" >&2
  exit 1
}

# Create a backup; just in case something goes wrong
$LXC cp "${db}" "${db}.bak"

# Delete all references to our domain.
exec $LXC sqlite3 "${db}" "
  BEGIN EXCLUSIVE;
  DELETE FROM records WHERE domain_id IN (
    SELECT id FROM domains WHERE name = $(SQL_Escape "${1}"));
  DELETE FROM comments WHERE domain_id IN (
    SELECT id FROM domains WHERE name = $(SQL_Escape "${1}"));
  DELETE FROM domainmetadata WHERE domain_id IN (
    SELECT id FROM domains WHERE name = $(SQL_Escape "${1}"));
  DELETE FROM cryptokeys WHERE domain_id IN (
    SELECT id FROM domains WHERE name = $(SQL_Escape "${1}"));
  DELETE FROM domains WHERE name = $(SQL_Escape "${1}");
  COMMIT"
