#!/bin/bash -e

# This script sets up a new slave zone.

# Copyright 2016, Markus Gutschke

export LC_ALL=C
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Use lxc, if necessary
LXC=
if lxc info pdns >&/dev/null; then
  LXC="lxc exec pdns --"
fi

db="/var/lib/powerdns/pdns.sqlite3"
SQL_Escape() { printf '%s' "'${*//\'/\'\'}'"; }

usage() {
  echo "${0##*/} { zone } { master ip address }" >&2
  exit 1
}

[ $# -eq 2 ] || usage
$LXC pdnsutil list-zone "${1}" >&/dev/null && {
  echo "Zone \"$1\" already exists" >&2
  exit 1
}
$LXC pdnsutil create-zone "${1}" || :
$LXC pdnsutil set-kind "${1}" slave
$LXC sqlite3 "${db}" "UPDATE domains SET master = $(SQL_Escape "${2}") WHERE name = $(SQL_Escape "${1}")"
$LXC pdns_control purge "${1}" || :
$LXC pdns_control reload || :
$LXC pdns_control retrieve "${1}" || :
