#!/bin/bash -e

# Block a domain that has been used for spam, by entering a bogus MX record.

# Copyright 2016, Markus Gutschke

export LC_ALL=C
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

[ $# -eq 1 ] && [[ "${1}" =~ ^[-a-z0-9]+\.[-a-z0-9]+\.[-a-z0-9]+$ ]] ||
  { echo "Usage: ${0##*/} <domain>" >&2; exit 1; }

# Use lxc, if necessary
LXC=
if lxc info pdns >&/dev/null; then
  LXC="lxc exec pdns --"
fi

db="/var/lib/powerdns/pdns.sqlite3"
SQL_Escape() { printf '%s' "'${*//\'/\'\'}'"; }

$LXC sqlite3 "${db}" "
  INSERT INTO records (domain_id, name, type, content, ttl, prio, disabled)
  SELECT id, $(SQL_Escape "${1}"), 'MX', 'localhost', 600, 10, 0
  FROM domains
  WHERE name = $(SQL_Escape "${1#*.}") AND
        1 NOT IN (SELECT 1
        FROM records
        WHERE name = $(SQL_Escape "${1}") AND
              domain_id IN (SELECT id
                            FROM domains
                            WHERE name = $(SQL_Escape "${1#*.}")));"

exec pdns-increase-serial "${1#*.}"
