#!/bin/bash -e

# For many "synchronous" DNS operations, an important primitive operation
# is the ability to increase the SOA serial number and to then wait for all
# slave DNS servers to see the change. This script performs the necessary
# operations to notify slaves and to wait for changes to propagate.

# Copyright 2016, Markus Gutschke

export LC_ALL=C
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

SQL_Escape() { printf '%s' "'${*//\'/\'\'}'"; }

# Find the zones served by our DNS server.
[ $# -eq 0 ] && zones="$(pdns-list-all-zones master native)" || zones="$@"

for i in ${zones}; do
  ser="$(pdnsutil increase-serial "${i}" 2>/dev/null |
         sed 's/.*\s\+//;t1;d;:1;q')"
  master="$(sqlite3 /var/lib/powerdns/pdns.sqlite3 "
            SELECT content
            FROM records
            WHERE type = 'NS' AND
                  domain_id IN (
                    SELECT id
                    FROM domains
                    WHERE name = $(SQL_Escape "$i")
                  ) AND 1 IN (
                    SELECT 1
                    FROM domains
                    WHERE InStr(records.content, domains.name) AND
                          domains.type != 'SLAVE')")"
  for ns in ${master}; do
    for j in $(seq 10); do
      [ "$(dig +tries=7 +time=8 +short @"${ns}" "${i}" SOA 2>/dev/null |
           awk '{ print $3 }')" != "${ser}" ] || break
      sleep 5
    done
  done
  pdns_control notify "${i}" >&/dev/null
  nameservers="$(sqlite3 /var/lib/powerdns/pdns.sqlite3 "
    SELECT content
    FROM records
    WHERE type = 'NS' AND domain_id IN (
      SELECT id
      FROM domains
      WHERE name = $(SQL_Escape "${i}"))")"
  for ns in ${nameservers}; do
    [[ "${master}" =~ .*"${ns}".* ]] && continue
    for j in $(seq 10); do
      [ "$(dig +tries=7 +time=8 +short @"${ns}" "${i}" SOA 2>/dev/null |
           awk '{ print $3 }')" != "${ser}" ] || break
      pdns_control notify-host "${i}" \
                   "$(host -tA ${ns} 2>/dev/null |
                      sed 's/.*\s\+//;t1;d;:1;q')" >&/dev/null
      sleep 10
    done
  done
done

unbound-control reload >&/dev/null || :

exit 0
